# Generated by Django 2.0.1 on 2019-05-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonhole', '0002_auto_20190512_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
