# Generated by Django 2.1.5 on 2019-05-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonhole', '0003_auto_20190512_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='id_number',
            new_name='idNo',
        ),
    ]
