# Generated by Django 2.0.1 on 2019-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonhole', '0004_auto_20190512_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeonholeaction',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
