# Generated by Django 2.0.1 on 2019-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonhole', '0007_auto_20190512_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='idNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pigeonholeaction',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
