# Generated by Django 2.0.1 on 2019-05-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonhole', '0009_remove_pigeonholeaction_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeonholeaction',
            name='timestamp',
            field=models.CharField(max_length=15),
        ),
    ]
